services:
  web:
    image: nginx:alpine
    container_name: webserver_nginx
    ports:
      - "8088:80"
    volumes:
      - /path/to/webserver/dist:/usr/share/nginx/html:rw
    restart: unless-stopped

networks:
  default:
    name: personal-website_default
    external: true
